# Generated by Django 4.1.1 on 2022-09-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='created',
            new_name='purchase_created',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='modified',
            new_name='purchase_modified',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='user_id',
            new_name='user',
        ),
    ]
